#!/bin/bash

#
# Copyright 2024, WiltonDB Software
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

set -e
set -x

pgdata=/var/lib/pgsql/data

/usr/bin/initdb -D $pgdata -U postgres -E UTF8 --locale=C --auth=ident --no-instructions

/usr/bin/sed -i "s|^\(host\s*all\s*all\s*\)127.0.0.1/32\s*ident$|\10.0.0.0/0               md5|" $pgdata/pg_hba.conf
/usr/bin/sed -i "s|^\(host\s*all\s*all\s*\)::1/128\s*ident$|\1::0/0                   md5|" $pgdata/pg_hba.conf
hba_replaced_count=$(grep "\(0.0.0.0/0\|::0/0\)\s*md5" $pgdata/pg_hba.conf | wc -l)
if test $hba_replaced_count -ne 2; then
    echo "can not change settings in $pgdata/pg_hba.conf"
    exit 1
fi

pushd $pgdata > /dev/null
/usr/bin/openssl req \
    -new \
    -x509 \
    -days 3650 \
    -nodes \
    -text \
    -batch \
    -out server.crt \
    -keyout server.key \
    -subj /CN=wiltondb_docker_host
popd > /dev/null

/usr/bin/pg_ctl start -D $pgdata

/usr/bin/psql -U postgres -d postgres -a << EOF
ALTER SYSTEM SET listen_addresses = '*';
ALTER SYSTEM SET max_connections = 256;
ALTER SYSTEM SET ssl = ON;
ALTER SYSTEM SET shared_preload_libraries = 'babelfishpg_tds','pg_stat_statements','system_stats';
CREATE USER wilton WITH SUPERUSER CREATEDB CREATEROLE PASSWORD 'wilton' INHERIT;
CREATE DATABASE wilton OWNER wilton;
EOF

/usr/bin/pg_ctl restart -D $pgdata

/usr/bin/psql -U postgres -d wilton -a << EOF
CREATE EXTENSION IF NOT EXISTS babelfishpg_tds CASCADE;
GRANT ALL ON SCHEMA sys to wilton;
ALTER SYSTEM SET babelfishpg_tsql.database_name = 'wilton';
ALTER DATABASE wilton SET babelfishpg_tsql.migration_mode = 'multi-db';
SELECT pg_reload_conf();
CALL sys.initialize_babelfish('wilton');
EOF

/usr/bin/pg_ctl stop -D $pgdata